// src/screens/JobDetailsScreen.tsx
import React, { useState, useEffect } from 'react';
import { StyleSheet, Text, View, ScrollView, TouchableOpacity, Alert, ActivityIndicator, Linking, Modal } from 'react-native';
import Toast from 'react-native-toast-message';
import { Ionicons } from '@expo/vector-icons';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { supabase } from '../services/supabase';
import { theme } from '../theme/colors';
import { GlassCard } from '../components/GlassCard';
import { generateJobPDF } from '../utils/pdfTemplate'; // 🚀 Requires your template file!

export default function JobDetailsScreen({ route, navigation }: any) {
    const { job, userProfile } = route.params;

    const [status, setStatus] = useState(job.status);
    const [isUpdating, setIsUpdating] = useState(false);
    const [isGeneratingPDF, setIsGeneratingPDF] = useState(false);
    const [assignedWorkerName, setAssignedWorkerName] = useState<string | null>(null);

    // Modal States
    const [isDeleteModalVisible, setDeleteModalVisible] = useState(false);

    const formattedId = `#TR-${job.id.substring(0, 4).toUpperCase()}`;
    const displayName = job.specs.jobName ? job.specs.jobName : formattedId;
    const companyName = userProfile?.company_name || 'Industrial Refinement';

    useEffect(() => {
        if (job.assigned_to) {
            fetchWorkerName(job.assigned_to);
        }
    }, []);

    const fetchWorkerName = async (workerId: string) => {
        const { data } = await supabase.from('profiles').select('name').eq('id', workerId).single();
        if (data) setAssignedWorkerName(data.name);
    };

    const updateStatus = async (newStatus: string) => {
        setIsUpdating(true);
        const updatePayload: any = { status: newStatus };
        if (newStatus === 'in_progress' && userProfile) {
            updatePayload.assigned_to = userProfile.id;
        }

        const { error } = await supabase.from('jobs').update(updatePayload).eq('id', job.id);

        if (error) {
            Toast.show({ type: 'error', text1: 'Error', text2: error.message });
        } else {
            setStatus(newStatus);
            if (newStatus === 'in_progress' && userProfile) setAssignedWorkerName(userProfile.name);
            Toast.show({ type: 'success', text1: 'Status Updated!', text2: `Job marked as ${newStatus.replace('_', ' ')}` });
        }
        setIsUpdating(false);
    };

    const confirmDelete = async () => {
        setDeleteModalVisible(false);
        setIsUpdating(true);
        const { error } = await supabase.from('jobs').delete().eq('id', job.id);

        if (error) {
            Toast.show({ type: 'error', text1: 'Error', text2: error.message });
            setIsUpdating(false);
        } else {
            Toast.show({ type: 'info', text1: 'Job Deleted', text2: `${displayName} has been removed.` });
            navigation.goBack();
        }
    };

    // 🚀 WHATSAPP EXPORT
    const handleWhatsAppShare = async () => {
        const message = `*🛠️ Work Order: ${displayName}*\n_Generated by ${companyName}_\n\n*Input:* ${job.specs.vIn}V\n*Output:* ${job.specs.vOut}V @ ${job.specs.amps}A\n\n*PRI:* ${job.results.primary.turns} turns (${job.results.primary.swg} SWG)\n*SEC:* ${job.results.secondary.turns} turns (${job.results.secondary.swg} SWG)\n\n*Est. Copper:* ${(job.results.primary.weightKg + job.results.secondary.weightKg).toFixed(2)} KG`;

        const url = `whatsapp://send?text=${encodeURIComponent(message)}`;

        try {
            const supported = await Linking.canOpenURL(url);
            if (supported) {
                await Linking.openURL(url);
            } else {
                Toast.show({ type: 'error', text1: 'WhatsApp Not Found', text2: 'Please install WhatsApp to use this feature.' });
            }
        } catch (error) {
            Toast.show({ type: 'error', text1: 'Error', text2: 'Could not open WhatsApp.' });
        }
    };

    // 🚀 PDF EXPORT
    const handleExportPDF = async () => {
        setIsGeneratingPDF(true);
        try {
            const html = generateJobPDF(job, companyName);
            const { uri } = await Print.printToFileAsync({ html });

            if (await Sharing.isAvailableAsync()) {
                await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
            } else {
                Toast.show({ type: 'error', text1: 'Sharing Unavailable', text2: 'Cannot share on this device.' });
            }
        } catch (error) {
            Toast.show({ type: 'error', text1: 'PDF Failed', text2: 'Could not generate document.' });
        } finally {
            setIsGeneratingPDF(false);
        }
    };

    return (
        <View style={styles.container}>
            <ScrollView style={styles.scrollArea} contentContainerStyle={{ paddingBottom: 40 }}>

                <View style={styles.header}>
                    <Text style={styles.systemText}>WORK ORDER ACTIVE</Text>
                    <Text style={styles.title}>{displayName}</Text>

                    <View style={styles.badgeRow}>
                        <View style={styles.badge}>
                            <Text style={styles.badgeText}>{status.toUpperCase().replace('_', ' ')}</Text>
                        </View>

                        {assignedWorkerName && (
                            <View style={[styles.badge, { marginLeft: 10, backgroundColor: 'rgba(52, 211, 153, 0.1)' }]}>
                                <Ionicons name="person-circle-outline" size={14} color={theme.primaryGlow} style={{ marginRight: 4 }} />
                                <Text style={[styles.badgeText, { color: theme.primaryGlow }]}>Assigned: {assignedWorkerName}</Text>
                            </View>
                        )}
                    </View>
                </View>

                {/* 🚀 EXPORT ACTION ROW */}
                <View style={styles.exportRow}>
                    <TouchableOpacity style={styles.whatsappBtn} onPress={handleWhatsAppShare}>
                        <Ionicons name="logo-whatsapp" size={20} color="#FFF" />
                        <Text style={styles.exportText}>WhatsApp</Text>
                    </TouchableOpacity>

                    <TouchableOpacity style={styles.pdfBtn} onPress={handleExportPDF} disabled={isGeneratingPDF}>
                        {isGeneratingPDF ? (
                            <ActivityIndicator color="#FFF" size="small" />
                        ) : (
                            <>
                                <Ionicons name="document-text" size={20} color="#FFF" />
                                <Text style={styles.exportText}>Export PDF</Text>
                            </>
                        )}
                    </TouchableOpacity>
                </View>

                <GlassCard style={styles.cardSpacing}>
                    <Text style={styles.sectionTitle}>Primary Winding</Text>
                    <View style={styles.dataRow}>
                        <Text style={styles.hugeNumber}>{job.results.primary.turns}</Text>
                        <Text style={styles.unitText}>Turns</Text>
                    </View>
                    <View style={styles.wireGaugeBox}>
                        <Text style={styles.wireGaugeLabel}>WIRE GAUGE</Text>
                        <Text style={styles.wireGaugeValue}>{job.results.primary.swg} SWG</Text>
                    </View>
                </GlassCard>

                <GlassCard style={styles.cardSpacing}>
                    <Text style={styles.sectionTitle}>Secondary Winding</Text>
                    <View style={styles.dataRow}>
                        <Text style={styles.hugeNumber}>{job.results.secondary.turns}</Text>
                        <Text style={styles.unitText}>Turns</Text>
                    </View>
                    <View style={styles.wireGaugeBox}>
                        <Text style={styles.wireGaugeLabel}>WIRE GAUGE</Text>
                        <Text style={styles.wireGaugeValue}>{job.results.secondary.swg} SWG</Text>
                    </View>
                </GlassCard>

                <Text style={styles.sectionTitle}>Job Actions</Text>

                {status === 'pending' && (
                    <TouchableOpacity style={[styles.actionBtn, { backgroundColor: theme.statusProgress }]} onPress={() => updateStatus('in_progress')} disabled={isUpdating}>
                        {isUpdating ? <ActivityIndicator color="#FFF" /> : <Text style={styles.actionBtnText}>Pick Up Job</Text>}
                    </TouchableOpacity>
                )}

                {status === 'in_progress' && (
                    <TouchableOpacity style={[styles.actionBtn, { backgroundColor: theme.statusDone }]} onPress={() => updateStatus('completed')} disabled={isUpdating}>
                        {isUpdating ? <ActivityIndicator color="#FFF" /> : <Text style={styles.actionBtnText}>Finish Job</Text>}
                    </TouchableOpacity>
                )}

                {/* 🚀 EVERYONE CAN SEE THE DELETE BUTTON */}
                <TouchableOpacity style={[styles.actionBtn, { backgroundColor: 'transparent', borderColor: '#EF4444', borderWidth: 1, marginTop: 15 }]} onPress={() => setDeleteModalVisible(true)} disabled={isUpdating}>
                    {isUpdating ? <ActivityIndicator color="#EF4444" /> : <Text style={[styles.actionBtnText, { color: '#EF4444' }]}>Delete Job Card</Text>}
                </TouchableOpacity>

            </ScrollView>

            {/* 🚀 FIXED SOLID DELETE MODAL */}
            <Modal
                animationType="fade"
                transparent={true}
                visible={isDeleteModalVisible}
                onRequestClose={() => setDeleteModalVisible(false)}
            >
                <View style={styles.modalOverlay}>
                    <View style={styles.modalContent}>
                        <Text style={styles.modalTitle}>Delete Job Card?</Text>
                        <Text style={styles.modalSubtitle}>
                            Are you sure you want to permanently delete{" "}
                            <Text style={{ color: theme.textMain, fontWeight: 'bold' }}>{displayName}</Text>?
                        </Text>

                        {status !== 'completed' && (
                            <View style={styles.warningBox}>
                                <Ionicons name="warning-outline" size={16} color="#EF4444" style={{ marginRight: 6 }} />
                                <Text style={styles.warningText}>
                                    Warning: This job is not yet completed. Deleting it will remove it from the workshop queue.
                                </Text>
                            </View>
                        )}

                        <View style={styles.modalButtonRow}>
                            <TouchableOpacity style={styles.modalCancelBtn} onPress={() => setDeleteModalVisible(false)}>
                                <Text style={styles.modalCancelText}>Cancel</Text>
                            </TouchableOpacity>

                            <TouchableOpacity style={styles.modalConfirmBtn} onPress={confirmDelete}>
                                <Text style={styles.modalDeleteBtnText}>Delete Job</Text>
                            </TouchableOpacity>
                        </View>
                    </View>
                </View>
            </Modal>
        </View>
    );
}

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: theme.background },
    scrollArea: { flex: 1, paddingHorizontal: 20 },
    header: { paddingTop: 20, paddingBottom: 15 },
    systemText: { color: theme.textMuted, fontSize: 10, fontWeight: 'bold', letterSpacing: 2, marginBottom: 4 },
    title: { color: theme.textMain, fontSize: 36, fontWeight: 'bold' },
    badgeRow: { flexDirection: 'row', marginTop: 10, alignItems: 'center' },
    badge: { backgroundColor: 'rgba(255,255,255,0.1)', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8, flexDirection: 'row', alignItems: 'center' },
    badgeText: { color: theme.textMuted, fontSize: 12, fontWeight: 'bold' },

    // EXPORT BUTTON STYLES
    exportRow: { flexDirection: 'row', gap: 12, marginBottom: 25 },
    whatsappBtn: { flex: 1, flexDirection: 'row', backgroundColor: '#25D366', paddingVertical: 14, borderRadius: 12, alignItems: 'center', justifyContent: 'center', gap: 8 },
    pdfBtn: { flex: 1, flexDirection: 'row', backgroundColor: '#475569', paddingVertical: 14, borderRadius: 12, alignItems: 'center', justifyContent: 'center', gap: 8 },
    exportText: { color: '#FFF', fontWeight: 'bold', fontSize: 14 },

    cardSpacing: { marginBottom: 20 },
    sectionTitle: { color: theme.primaryGlow, fontSize: 18, fontWeight: 'bold', marginBottom: 10 },
    dataRow: { flexDirection: 'row', alignItems: 'baseline', marginBottom: 15 },
    hugeNumber: { color: theme.textMain, fontSize: 48, fontWeight: 'bold', marginRight: 8 },
    unitText: { color: theme.textMuted, fontSize: 16, fontWeight: '600' },
    wireGaugeBox: { backgroundColor: 'rgba(0,0,0,0.3)', padding: 15, borderRadius: 10 },
    wireGaugeLabel: { color: theme.textMuted, fontSize: 10, fontWeight: 'bold', letterSpacing: 1, marginBottom: 4 },
    wireGaugeValue: { color: theme.textMain, fontSize: 20, fontWeight: 'bold' },
    actionBtn: { paddingVertical: 16, borderRadius: 12, alignItems: 'center', marginTop: 10 },
    actionBtnText: { color: theme.background, fontSize: 16, fontWeight: 'bold' },

    // FIXED MODAL STYLES
    modalOverlay: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.85)', justifyContent: 'center', alignItems: 'center', padding: 20 },
    modalContent: { width: '100%', padding: 24, backgroundColor: '#121212', borderRadius: 16, borderColor: theme.glassBorder, borderWidth: 1, shadowColor: '#000', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.8, shadowRadius: 20, elevation: 15 },
    modalTitle: { color: theme.textMain, fontSize: 22, fontWeight: 'bold', marginBottom: 8 },
    modalSubtitle: { color: theme.textMuted, fontSize: 14, marginBottom: 15, lineHeight: 20 },
    warningBox: { flexDirection: 'row', backgroundColor: 'rgba(239, 68, 68, 0.1)', padding: 12, borderRadius: 8, marginBottom: 20, borderWidth: 1, borderColor: 'rgba(239, 68, 68, 0.3)' },
    warningText: { color: '#EF4444', fontSize: 13, flex: 1, lineHeight: 18 },
    modalButtonRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 10 },
    modalCancelBtn: { flex: 1, paddingVertical: 16, alignItems: 'center', marginRight: 10, borderRadius: 12, borderWidth: 1, borderColor: theme.glassBorder },
    modalCancelText: { color: theme.textMuted, fontWeight: 'bold', fontSize: 16 },
    modalConfirmBtn: { flex: 1, backgroundColor: '#EF4444', paddingVertical: 16, alignItems: 'center', borderRadius: 12, marginLeft: 10 },
    modalDeleteBtnText: { color: '#FFF', fontWeight: 'bold', fontSize: 16 }
});