// src/utils/pdfTemplate.ts

export const generateJobPDF = (job: any, companyName: string) => {
    const jobId = job.specs.jobName || `#TR-${job.id.substring(0, 4).toUpperCase()}`;
    const date = new Date(job.created_at).toLocaleDateString();

    return `
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
        <style>
          body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 40px; color: #333; }
          .header { text-align: center; border-bottom: 3px solid #10B981; padding-bottom: 20px; margin-bottom: 30px; }
          .company { font-size: 28px; font-weight: bold; color: #0F172A; text-transform: uppercase; letter-spacing: 2px; }
          .title { font-size: 14px; color: #64748B; letter-spacing: 1px; margin-top: 5px; }
          .job-box { background-color: #F8FAFC; border: 1px solid #E2E8F0; padding: 20px; border-radius: 8px; margin-bottom: 30px; }
          .job-id { font-size: 20px; font-weight: bold; color: #0F172A; }
          .job-date { font-size: 14px; color: #64748B; margin-top: 5px; }
          .section-title { font-size: 18px; font-weight: bold; color: #10B981; margin-bottom: 15px; border-bottom: 1px solid #E2E8F0; padding-bottom: 5px; }
          
          table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
          th, td { text-align: left; padding: 12px; border-bottom: 1px solid #E2E8F0; }
          th { font-size: 12px; color: #64748B; text-transform: uppercase; letter-spacing: 1px; }
          td { font-size: 16px; font-weight: bold; color: #0F172A; }
          
          .footer { margin-top: 50px; text-align: center; font-size: 12px; color: #94A3B8; }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="company">${companyName}</div>
          <div class="title">OFFICIAL WORK ORDER SPECIFICATION</div>
        </div>

        <div class="job-box">
          <div class="job-id">Ref: ${jobId}</div>
          <div class="job-date">Generated on: ${date}</div>
        </div>

        <div class="section-title">Design Parameters</div>
        <table>
          <tr>
            <th>Input Voltage</th>
            <th>Output Voltage</th>
            <th>Target Current</th>
            <th>Bobbin Length</th>
          </tr>
          <tr>
            <td>${job.specs.vIn} V</td>
            <td>${job.specs.vOut} V</td>
            <td>${job.specs.amps} A</td>
            <td>${job.specs.bobbinLength}"</td>
          </tr>
        </table>

        <div class="section-title">Winding Instructions</div>
        <table>
          <tr>
            <th>Coil</th>
            <th>Total Turns</th>
            <th>Wire Gauge (SWG)</th>
            <th>Est. Copper Weight</th>
          </tr>
          <tr>
            <td style="color: #64748B;">PRIMARY</td>
            <td>${job.results.primary.turns}</td>
            <td>${job.results.primary.swg}</td>
            <td>${job.results.primary.weightKg.toFixed(3)} kg</td>
          </tr>
          <tr>
            <td style="color: #64748B;">SECONDARY</td>
            <td>${job.results.secondary.turns}</td>
            <td>${job.results.secondary.swg}</td>
            <td>${job.results.secondary.weightKg.toFixed(3)} kg</td>
          </tr>
        </table>

        <div class="footer">
          Document generated by Industrial Refinement Software.<br/>
          Total Estimated Copper: ${(job.results.primary.weightKg + job.results.secondary.weightKg).toFixed(3)} kg
        </div>
      </body>
    </html>
    `;
};